
[functions.aggiorna-iscrizioni]
enabled = true
verify_jwt = true
import_map = "./functions/aggiorna-iscrizioni/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/aggiorna-iscrizioni/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/aggiorna-iscrizioni/*.html" ]

[functions.notifica-prepartita]
enabled = true
verify_jwt = true
import_map = "./functions/notifica-prepartita/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/notifica-prepartita/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/notifica-prepartita/*.html" ]

[functions.call_fcm_function]
enabled = true
verify_jwt = true
import_map = "./functions/call_fcm_function/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/call_fcm_function/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/call_fcm_function/*.html" ]

[functions.notifica-annullamento-partita]
enabled = true
verify_jwt = true
import_map = "./functions/notifica-annullamento-partita/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/notifica-annullamento-partita/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/notifica-annullamento-partita/*.html" ]
