name: Aggiorna partite visibili ogni 5 min circa

on:
  schedule:
    - cron: '*/5 * * * *'  # ogni 5 minuti
  workflow_dispatch:        # permette esecuzione manuale

jobs:
  call-function:
    runs-on: ubuntu-latest
    steps:
      - name: Esegui chiamata HTTP alla funzione
        run: |
          curl -X POST https://ugtxgylfzblkvudpnagi.functions.supabase.co/aggiorna-iscrizioni \
          -H "Authorization: Bearer ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}"
